### ISSUE TITLE
Reconcile migration and existing keychain with new idw/ceramic

### ISSUE THREAD

**Issue by zachferland** [3box/3id-connect#65]
Ideal upgrade path still means supporting what is currently in 3boxjs (no upgrade needed to migrate) 

some work on this earlier, likely best path is developing legacy and new idw/connect separately, and then they run as two logical services in iframe consuming their rpc calls, legacy calls continue to work, migration takes place there, migration will run and take current serialized state and add to cereamic, if migration has taken place, will map legacy rpc calls to new 'service'

**Comment by oed** [comment]
Can you schedule some time to sync on this once you have a better view here?
