### ISSUE TITLE
Upgrade and test 3id-connect with the newest versions of ceramic, cids, etc.

### ISSUE THREAD

**Issue by stbrody** [3box/3id-connect#99]
Wasn't sure who made sense to take this on so I assigned it to both @PaulLeCam and @zachferland for now, although probably only one of them needs to pick this up.  But now that release candidates of the ceramic core packages are out with upgraded ipfs, cids, and multiformats, it would be good to make sure that 3id connect works with them so we can start telling people who are having version incompatibility errors that they can upgrade to the release candidate and use it.

**Comment by zachferland** [comment]
No blockers here in deploying latest RC. Current 3id-connect release works against RC daemon (0.20.0-rc.11)

Didnt up dependencies in 3id-connect yet, that will be easier once latest stuff is merged in finalized (if there is actually any code changes), and then can be released again at that time. But most importantly no blockers for releasing latest ceramic RC on our infra, 3id-connect should continue to work as expected.
